---
title: "ISPM"
output:
  pdf_document:
    fig_caption: yes
    toc: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.height = 3, warning = F)
```

```{r cargar paquetes}

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(MPAtools)
  library(reshape)
  library(stargazer)
  library(ggExtra)
})

```

```{r cargar datos}

# abnt <- read.csv("./Datos/12082016 ISPM Especifico.csv", sep = ";", stringsAsFactors = F) %>%
#   mutate(NT = as.numeric(NT), a = as.numeric(a), b=as.numeric(b))
# 
# datos <- read.csv("./Datos/peces_completado.csv", sep=";")%>%
#   filter (!GeneroEspecie == "Urobatis spp.") %>%
#   mutate(id = paste(Dia, Mes, Ano, Sitio, Transecto))
# 
# datos2 <- datos %>%
#   select(id, Genero, Especie, GeneroEspecie, Talla, Abundancia) %>%
#   complete(id, nesting(Genero, Especie, GeneroEspecie), fill = list(Talla = NA, Abundancia = 0))
# 
# datos <- datos %>%
#   select(-GeneroEspecie, -Talla, -Abundancia, -Genero, -Especie) %>%
#   group_by(id, Dia, Mes, Ano, Estado, Comunidad, Sitio, Latitud, Longitud, Habitat, Zonificacion, TipoProteccion, ANP, BuzoMonitor, HoraInicial, HoraFinal, ProfundidadInicial, ProfundidadFinal, Temperatura, Visibilidad, Corriente, Transecto) %>%
#   summarize(N=n()) %>%
#   select(-N) %>%
#   full_join(datos2, by ="id") %>%
#   left_join(abnt, by = "GeneroEspecie") %>%
#   mutate(Talla = as.numeric(as.character(Talla)), Abundancia = as.numeric(as.character(Abundancia))) %>%
#   mutate(Biomasa = Abundancia*a*(Talla^b)) %>%
#   mutate(TransectNumber = Transecto, Site = Comunidad, Year = Ano, Zone = Zonificacion, SizeClass = Talla) %>%
#   filter(!is.na(Abundancia)) %>%
#   ungroup()

datos <- read.csv("./Datos/limpios/pecesISPM_JCVD16082016.csv", sep=";") %>%
  filter(!GeneroEspecie == "Urobatis sp.") %>%
  filter(!GeneroEspecie == "Kiphosus sp.") %>%
  filter(!GeneroEspecie == "Muraena sp.")

```

# Indicadores Peces (Pesca vs. No Pesca)

## Densidad promedio por zona

```{r}

N <- density(datos, "Bahia de Kino")
mpa_plot2(N, "d")

```

```{r}

NP <- N %>%
  group_by(Ano, Zonificacion) %>%
  summarize(N = mean (D)) %>%
  filter(Zonificacion == "Zona de Pesca ")
modelNP <- lm(N ~ Ano, data = NP)

NR <- N %>%
  group_by(Ano, Zonificacion) %>%
  summarize(N = mean (D)) %>%
  filter(Zonificacion == "Zona de no Pesca ")
modelNR <- lm(N ~ Ano, data = NR)

N2 <- datos %>%
  mutate(Temperatura = as.numeric(as.character(Temperatura))) %>%
  group_by(Ano, Zonificacion, Sitio, Transecto) %>%
  summarize(N = sum(Abundancia, na.rm=T), Temp = mean(Temperatura, na.rm = T)) %>%
  group_by(Ano, Zonificacion) %>%
  summarize(N = mean(N, na.rm=T), Temp = mean(Temp, na.rm=T))

modelNT <- lm(N ~ Ano + Zonificacion + Temp, data = N2)

stargazer(modelNP, modelNR, modelNT, type = "latex", dep.var.caption = "Densidad", omit.stat = c("n"), keep.stat = "aic", title = "Modelos lineales describiendo cambios en las densidades promedio por zona para (1) Pesca y (2) No Pesca.")

```



## Riqueza promedio por zona

```{r}

S <- richness(data = datos, location = "Bahia de Kino")
mpa_plot2(S, "s")

```

```{r}

 SP <- S %>%
  group_by(Ano, Zonificacion) %>%
  summarize(S = mean(S)) %>%
  filter(Zonificacion == "Zona de Pesca ")
modelSP <- lm(S ~ Ano, data = SP)

 SR <- S%>%
  group_by(Ano, Zonificacion) %>%
  summarize(S = mean(S)) %>%
  filter(Zonificacion == "Zona de no Pesca ")
modelSR <- lm(S ~ Ano, data = SP)

```


## Biomasa promedio por zona

```{r}

B <- datos %>%
  group_by(Ano, Zonificacion, Sitio, Transecto) %>%
  summarize(B1 = sum(Biomasa, na.rm=T)) %>%
  group_by(Ano, Zonificacion) %>%
  summarize(B = mean(B1, na.rm=T), BDS = sd(B1, na.rm=T))

ggplot(data = B, aes(x = Ano, y = B, col = Zonificacion))+
  geom_line()+
  geom_point() +
  geom_errorbar(aes(ymin=B-BDS,ymax=B+BDS), width = 0.2)+
  theme_bw()+
  labs(x="A침o", y="Biomasa (gramos / transecto)")+
  scale_color_brewer(palette = "Set1")

```

## Nivel tr칩fico promedio por zona

```{r}

NT <- datos %>%
  group_by(Ano, Zonificacion) %>%
  summarize(NT1 = mean(NT, na.rm=T), NTS = sd(NT, na.rm=T))

ggplot(data = NT, aes(x = Ano, y = NT1, col = Zonificacion))+
  geom_line()+
  geom_point() +
  geom_errorbar(aes(ymin=NT1-NTS,ymax=NT1+NTS), width = 0.2)+
  theme_bw()+
  labs(x="A침o", y="Nivel tr칩fico medio")+
  scale_color_brewer(palette = "Set1")

```

## NT peces

```{r}

NT_P <- datos %>%
  filter(Zonificacion == "Zona de Pesca ") %>%
  filter(!is.na(NT)) %>%
  mutate(NT = floor(NT)) %>%
  group_by(Ano, NT) %>%
  summarize(Abundancia = mean(Abundancia)) %>%
  spread(Ano, Abundancia)


rows <- unique(NT_P$NT)

NT_P <- as.data.frame(NT_P[-1])

rownames(NT_P) <- rows

pro.NT_P<- prop.table(as.matrix(NT_P),2)

Xsq <- chisq.test(pro.NT_P, correct = T)

```


\clearpage

# Invertebrados

```{r, eval=F}

# datos_inv <- read.csv("./Datos/invertebrados_completado.csv", sep=",")%>%
#   mutate(id = paste(Dia, Mes, Ano, Sitio, Transecto))
# 
# datos_inv2 <- datos_inv %>%
#   select(id, Genero, Especie, GeneroEspecie, Abundancia) %>%
#   complete(id, nesting(Genero, Especie, GeneroEspecie), fill = list(Abundancia = 0))
# 
# datos_inv <- datos_inv %>%
#   select(-GeneroEspecie, -Abundancia, -Genero, -Especie) %>%
#   group_by(id, Dia, Mes, Ano, Estado, Comunidad, Sitio, Latitud, Longitud, Habitat, Zonificacion, TipoProteccion, ANP, BuzoMonitor, HoraInicial, HoraFinal, ProfundidadInicial, ProfundidadFinal, Temperatura, Visibilidad, Corriente, Transecto) %>%
#   summarize(N=n()) %>%
#   select(-N) %>%
#   full_join(datos_inv2, by ="id") %>%
#   filter(!is.na(Abundancia)) %>%
#   group_by(id, Dia, Mes, Ano, Estado, Comunidad, Sitio, Latitud, Longitud, Habitat, Zonificacion, TipoProteccion, ANP, BuzoMonitor, HoraInicial, HoraFinal, ProfundidadInicial, ProfundidadFinal, Temperatura, Visibilidad, Corriente, Transecto, Genero, Especie, GeneroEspecie) %>%
#   summarize(Abundancia = sum(Abundancia))

invert <- read.csv("~/GitHub/ISPM/Datos/limpios/invertebradosISPM_JCVD16082016.csv")

```



